# Database configuration (POSTGRESQL - Render Free DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/move
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server configuration
server.port=8080

# Spring Security (Disabled for initial development)
# spring.security.user.name=user
# spring.security.user.password=password
