# Database
spring.datasource.url=jdbc:postgresql://ep-odd-shadow-ae6r82q1-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dZhyJr2pt3Wm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# JWT
jwt.secret=bW92ZS1zdXBlci1zZWNyZXQta2V5LWZvci1wcm9kdWN0aW9uLW11c3QtYmUtYXQtbGVhc3QtMjU2LWJpdHM=
jwt.expiration=86400000

# Google OAuth
google.client.id=

# PayFast
payfast.merchant.id=34468035
payfast.merchant.key=udwvlsbq9shwu
payfast.passphrase=brel1nX.comm
payfast.sandbox=true

# Twilio — paste your new credentials here
twilio.account.sid=ACb6e949bab72fae93fea09aa9c27d081d
twilio.auth.token=2df4303dfec3ff01bcf5b88d4fdb9c3a
twilio.verify.service.sid=VAe834a1ffa6e58f267e0e0c96f34c756b
